### ISSUE TITLE
sql where group = 10 is error

### ISSUE THREAD

**Issue by wuchuguang** [jstayton/Miner#13]
where `group` = 10 is ok

**Comment by wuchuguang** [comment]
$this->where('group', 10);

**Comment by jstayton** [comment]
Hi wachuguang,

I'm not sure I understand. Can you post some more code and the resulting SQL that's failing? Thanks.

**Comment by wuchuguang** [comment]
$miner = new Miner(...);
$miner->from('my_table');
$miner->where('group', 10);
$miner->select('*');
$sql = $miner->getStatement();
use $sql to execute in sql client , is report error.

**Comment by ArabCoders** [comment]
i think what he means is that if you use reserved keyword such as "group, from, to" they get interpreted as sql keyword not a field name, i had the same problem with my own sql builder, the best option is to escape the fieldnames so instead of the query being `select * from my_table where group = 10` it becomes
```sql
SELECT * FROM `my_table` WHERE `group` = 10
```

**Comment by jstayton** [comment]
@wuchuguang I'm very sorry for never responding to you here. As my silence likely hinted, I stopped maintaining this project long ago. I'm now officially deprecating it to make that clear.

If you'd like to continue supporting a forked version, please reach out on Twitter ([@kidjustino](https://twitter.com/kidjustino)) to have it listed in the README.
